name: Deploy the application to Google Cloud Run

on: 
  push:
    branches: 
      - 'master'

jobs:
  deploy:
    name: Deploy chrishawley.io
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
        
      - name: Checkout the repository
        run: docker build . --file Dockerfile --tag gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/${{ secrets.GCLOUD_APP_NAME }}
  
      - name: Log into GCP Docker Registry
        uses: actions/gcloud/auth@master
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}

      - name: Configure Docker to use GCP
        uses: actions/gcloud/cli@master
        with:
          args: "auth configure-docker --quiet"
        
      - name: Push image to GCP CR
        uses: actions/gcloud/cli@master
        with:
          entrypoint: sh
          args: -c "docker push gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/${{ secrets.GCLOUD_APP_NAME }}"

      - name: Install beta commands and deploy on cloud run
        uses: actions/gcloud/cli@master
        with:
          args: "components install beta --quiet && gcloud beta run deploy ${{ secrets.GCLOUD_APP_NAME }} --quiet --image gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/${{ secrets.GCLOUD_APP_NAME }} --project ${{ secrets.GCLOUD_PROJECT_ID }} --region us-central1 --platform managed"
                    
