name: Deploy the application to Google Cloud Run

on: 
  push:
    tags: 
      - '*'

jobs:
  deploy:
    name: Deploy chrishawley.io
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2.3.5
        
      - name: Checkout the repository
        run: docker build . --file Dockerfile --tag "gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/${{ secrets.GCLOUD_APP_NAME }}:latest"
  
      - name: Log into GCP Docker Registry
        uses: actions-hub/gcloud@master
        env:
          APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD_AUTH }}
          PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}

      - name: Configure Docker to use GCP
        uses: actions-hub/gcloud@master
        with:
          args: "auth configure-docker --quiet"
        
      - name: Push image to GCP CR
        uses: actions-hub/gcloud@master
        with:
          entrypoint: sh
          args: -c "docker push gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/${{ secrets.GCLOUD_APP_NAME }}"

      - name: Install beta commands and deploy on cloud run
        uses: actions-hub/gcloud@master
        with:
          args: "components install beta --quiet && gcloud beta run deploy ${{ secrets.GCLOUD_APP_NAME }} --quiet --image gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/${{ secrets.GCLOUD_APP_NAME }} --project ${{ secrets.GCLOUD_PROJECT_ID }} --region us-central1 --platform managed"
                    
