name: Deploy the application to Google Cloud Run

on: 
  push:
    branches:
      - "master"

jobs:
  deploy:
    name: Deploy chrishawley.io
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v5
      
      - uses: google-github-actions/auth@v3
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          credentials_json: ${{ secrets.GCLOUD_AUTH }}

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v3
        with:
          service: ${{ secrets.GCLOUD_APP_NAME }}
          source: './'   
  
